# Example development configuration
# Rename to dev.yaml to use
yahboom_pick_and_place:
  dataloader:
    init:
      host: "127.0.0.1"
      port: 6379
      db: 0
      password: null  # No password for development
    process:
      queue: "camera_frames"
      wait: true
      timeout: 0.5

  calibrate:
    init:
      binary_threshold: 130  # Adjusted for development environment

  detect:
    init:
      color_hsv_thresholds:
        red: [[0, 43, 46], [10, 255, 255]]
        green: [[35, 43, 46], [77, 255, 255]]

  # armcontrol configs ...
