# Example development configuration
# Rename to dev.yaml to use
yahboom_pick_and_place:
  pipeline: "yahboom_pick_and_place"

  redis:
    host: "127.0.0.1"
    port: 6379
    db: 0
    password: null

  handlers:
    data_loader:
      process:
        queue: "camera_frames"
        wait: true
        timeout: 0.5

    calibrate:
      init:
        binary_threshold: 130  # Adjusted for development environment

    detect:
      init:
        color_hsv_thresholds:
          red: [[0, 43, 46], [10, 255, 255]]
          green: [[35, 43, 46], [77, 255, 255]]

    arm_control:
      init:
        remote_addr: "192.168.1.34"
        task: "pick_and_place"
        grasp_offset: [-0.02, -0.005]
        init_angles: [43, 0, 0, -80, -6, -6]
        coord_config:
          pre_grasp_z: 180
          grasp_z: 130
          post_grasp_z: 200
          place:
            red: [75, 230, 130, -175, 0, -45]
            green: [10, 230, 130, -175, 0, -45]
            blue: [-70, 230, 130, -175, 0, -45]
            yellow: [140, 230, 130, -175, 0, -45]
          stack:
            first: [135, -155, 130, -175, 0, -45]
            delta_z: 30
        gripper_config:
          open: 100
          close: 10
      process:
        speed: 20
        delay: 3
